### ISSUE TITLE
kmwString on NPM

### ISSUE THREAD

**Issue by mk-pmb** [keymanapp/keyman-tools#1]
Thank you for your article "[A more UTF-32 aware JavaScript String library](http://marc.durdin.net/2012/04/a-more-utf-32-aware-javascript-string-library/)" and your code. Could you consider making a Node.js module from it and publishing it on NPM?

**Comment by tavultesoft** [comment]
Yes, we would consider it, however the library needs updating so that it doesn't extend String but is rather a separate class operating on strings, for compatibility and stability reasons, first.
